### ISSUE TITLE
时光邮局能做成小程序？能做的话，多少money？

### ISSUE THREAD

**Issue by wmxerni** [soxft/TimeMail#7]

**Comment by soxft** [comment]
事实上我们有现成的小程序，由于认为微信限制过多，已经在微信下架。请联系 cc @michangyu

**Comment by wmxerni** [comment]
有关网站、公众号内的问题请前往；1、微信小程序：爱折腾的医学生，在小程序内的文章留言；2、前往
    
        https://mznzd.com
    
    ，登录网站，通过网站给我们评论留言；此邮箱不回复有关网站及公众号内相关的消息，有关工作及生活上的邮件，在看到邮件后，会第一时间给您回复，谢谢。
